# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
exclude: |
  (?x)^(
    .*/versioneer\.py|.*/_version\.py|.*/.*\.svg|percy/tests/test_aux_files/.*|percy/examples/.*
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    exclude_types: ["json", "yaml"]
  - id: check-ast
  - id: fix-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.2
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
  - id: check-renovate
# Notes:
# - By default, `black` uses a line-length of 88.
# - `isort` will conflict with `black`, if not properly configured
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", --line-length=120]
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    args: [--line-length=120]
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.2
  hooks:
  - id: pylint
    args: ["--rcfile=.pylintrc"]
# TODO re-enable the static analyzer, when the rest of the dev tools have
# stabilized.
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.6.1
#  hooks:
#  - id: mypy
#    # `mypy` is run as a system script to ensure that it is checking against
#    # the libraries we have installed to the environment.
#    language: system
#    args: [--config-file=.mypy.ini, "--cache-dir=/dev/null"]
# `pre-commit` no longer provides a hook for `pytest`, by design
- repo: local
  hooks:
  - id: pytest
    language: system
    name: pytest
    always_run: true
    pass_filenames: false
    entry: make test
  - id: pytest-cov
    language: system
    name: pytest-cov
    always_run: true
    pass_filenames: false
    entry: make test-cov
