name: percy

dependencies:
  - black
  - isort
  - conda-forge::mypy
  - python=3.11
  - pytest
  - pytest-cov
  - pylint
  - pip
  - conda-forge::click>=8.1.6
  - conda
  - jinja2
  - pyyaml
  - requests
  - ruamel.yaml
  - conda-build
  - jsonschema
  - pre-commit
