name: percy
channels:
  - defaults

dependencies:
  - black
  - isort
  - make
  - mypy
  - python>=3.8
  - pytest
  - pytest-cov
  - pytest-xdist
  - pylint
  - pip
  - click>=8.1.6
  - conda
  - jinja2
  - pyyaml
  - requests
  - ruamel.yaml
  - conda-build
  - jsonschema
  - pre-commit
