name: Python package
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Update conda
        run: |
          conda update -n base -c defaults conda
          conda install -n base conda-libmamba-solver
          source $CONDA/etc/profile.d/conda.sh
          conda env create -f environment.yaml --experimental-solver=libmamba --name percy
          conda init bash
          conda activate percy
      - name: Install dev and test dependencies
        run: |
          source $CONDA/etc/profile.d/conda.sh
          pip install -e .[dev]
  # Runs pre-commit checks, including static analyzer
  # For now, we only run tests on the latest supported version
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        # Create a conda environment with all of percy's dependencies. Then
        # run pre-commit, which triggers a handful of `make` commands
        run: |
          conda update -n base -c defaults conda
          source $CONDA/etc/profile.d/conda.sh
          conda init bash
          make environment
          conda activate percy
      - uses: pre-commit/action@v3.0.0
