name: Python package
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Update conda
        run: |
          conda update -n base -c defaults conda
          conda install -n base conda-libmamba-solver
          source $CONDA/etc/profile.d/conda.sh
          conda env create -f environment.yaml --solver=libmamba --name percy
          conda init bash
          conda activate percy
      - name: Install dev and test dependencies
        run: |
          source $CONDA/etc/profile.d/conda.sh
          pip install -e .[dev]
