# Runs pre-commit checks, including static analyzer.
# For now, we only run tests on the latest supported version of Python.

on:
  push:
    branches:
      - main
  pull_request:

name: pre-commit checks and tests

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        # Create a conda environment with all of percy's dependencies. Then
        # run pre-commit, which triggers a handful of `make` commands
        run: |
          conda update -n base -c defaults conda
          source $CONDA/etc/profile.d/conda.sh
          conda init bash
          conda env create -f environment.yaml --name percy --force
          conda run --name percy pip install .
          conda activate percy
          make pre-commit
